Develop
funera1/gofmtal pull request #1
Opened 2022-08-18 05:25 UTC by funera1

2022-08-18 05:26 UTC, tenntenn commented on cmd/root.go
>  			log.Fatal(err)
エラーを返すようにする。
`log.Fatal`は`os.Exit`（プログラムの終了）を呼ぶのでエラー処理としては適切ではない。

2022-08-18 05:27 UTC, tenntenn commented on cmd/root.go
>  	Run: func(cmd *cobra.Command, args []string) {
`RunE`の方がよい
https://pkg.go.dev/github.com/spf13/cobra#Command.RunE

2022-08-18 05:27 UTC, tenntenn commented on cmd/root.go
>  func GetAst(code string) *ast.File {
エラーを返すようにする。

2022-08-18 05:28 UTC, tenntenn commented on cmd/root.go
>  func GetAst(code string) *ast.File {
ファイル名をもらってきた方が良さそう。
fsetも返すようにした方がよさそう。

2022-08-18 05:29 UTC, tenntenn commented on cmd/root.go
> +		// cmntにはgo fmt targetの出力結果が入力されることを期待
`gofmt`コマンドを使わずに、`go/format`パッケージを使うと、文字列またはASTのノードをフォーマットされたソースコードに変換できる。
https://pkg.go.dev/go/format

2022-08-18 05:30 UTC, tenntenn commented on cmd/root.go
> +		// cmntにはgo fmt targetの出力結果が入力されることを期待
ここは単純にファイル名があれば、`parser.ParseFile`でパースできる

2022-08-18 05:30 UTC, tenntenn commented on cmd/root.go
>  		ast := GetAst(code)
ファイル名を渡す

2022-08-18 05:32 UTC, tenntenn commented on cmd/root.go
> +		// cmntにはgo fmt targetの出力結果が入力されることを期待
`gofmt`はあとからかける

2022-08-18 05:33 UTC, tenntenn commented on cmd/root.go
> +		codeBlocks := DevideIntoCommentAndNonComment(code, ast)
ASTだけでコメントは取れる。

2022-08-18 05:34 UTC, tenntenn commented on cmd/root.go
> +		print(format_code)
printはstderrに出力するので、fmt.Fprintlnとかで、外部からWriterを指定できるようにしておいて、デフォルトはos.Stdoutにしておくとテストが楽。

2022-08-18 05:35 UTC, tenntenn commented on cmd/root.go
> +		format_code := ""
Goにはゼロ値があるので、宣言だけで十分。
`_`を使ってスネークケースは書かない。
var formatedCode string

2022-08-19 08:05 UTC, funera1 commented
ローカルでマージコンフリクトを修正したせいでFile Changedが壊れてしまいました

2022-08-23 08:27 UTC, funera1 commented
前回はastでコメントを抜き出してコメント内部のコード部分にだけformatをかけていたのですが、必要ないと感じたのでやめました。
理由としては、コメント内のコードと普通のコードを同じようにformatをかけるとインデントが崩れたのでastでコメントだけ抜き出していたのですが、あとから全体のformatをかければ解決したからです。

2022-08-24 03:07 UTC, tenntenn requested changes
レビューしました！

2022-08-24 03:07 UTC, tenntenn commented on cmd/root.go
> +	"io/ioutil"
`ioutil`は現在非推奨になってるので、`os`や`io`パッケージを代わりに使うと良いです。

2022-08-24 03:07 UTC, tenntenn commented on cmd/root.go
> +		return
naked return(空のreturn文）は可読性が悪いので、できれば使用しない方が良いです。

2022-08-24 03:07 UTC, tenntenn commented on cmd/root.go
> +func FormatCode(filename string) (formattedCode string, err error) {
named return value（名前付き戻り値）は、できる限り使用せず、ドキュメンテーションまたは`defer`文を使った戻り値の変更のみ使用すると良いです。

2022-08-24 03:07 UTC, tenntenn commented on cmd/root.go
> +	return strings.HasSuffix(filename, ".go")
`filepath.Ext`関数を使うとよいでしょう。

2022-08-24 03:07 UTC, tenntenn commented on cmd/root.go
> +func GofmtalMain(targetfile string, writer io.Writer) (err error) {
named return valueとnaked returnを修正する

2022-08-24 03:07 UTC, tenntenn commented on cmd/root.go
> +	doc := p.Parse(code)
これって、`go/parser.ParseFile`関数などを使用して、ASTにしてからコメントだけを取り出すコードじゃなくてもうまく動きます？

2022-08-31 02:17 UTC, funera1 commented
挙動
$ cat testdata2.go
```
package main

/*
	  func test2() {
				var a int;;;;
			}
*/
func test2() {
	var a int
}
```
$ gofmtal testdata2.go
```
package main

/*

	func test2() {
		var a int
	}

*/
*/func test2() {
	var a int
}
```

2022-08-31 02:18 UTC, funera1 commented
processFileはまだ途中なのでコードの整理とかはまだできてないです

2022-08-31 02:55 UTC, tenntenn commented on cmd/root.go
> +		for j, cmnt := range cmnts.List {
一度結合して、フォーマットかけて、Commentを作り直す。

2022-08-31 02:57 UTC, tenntenn commented on cmd/root.go
> +		f.Comments[i] = cmnts
ここで`cmnts`をダンプして確認するといいかも

2022-09-08 06:19 UTC, funera1 commented
一旦マージ

2022-09-08 06:24 UTC, merged